# Generated by Django 3.1.1 on 2021-11-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(default='00/00/000', max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('date_of_enrollment', models.DateField(default='00/00/000', max_length=50)),
                ('quiz_scores', models.TextField(default='None')),
                ('python_entry_level', models.TextField(default='None')),
                ('AWS_practitioner_exams', models.TextField(default='None')),
                ('python_associate_level_exam', models.TextField(default='None')),
                ('blockchain_exam', models.TextField(default='None')),
                ('aws_ml_exam', models.TextField(default='None')),
                ('dissertation_score', models.TextField(default='None')),
                ('date_of_graduation', models.DateField(default='00/00/000', max_length=50)),
                ('job_placement', models.TextField(default='None')),
            ],
        ),
    ]
