# Generated by Django 3.1.1 on 2021-11-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0003_auto_20211127_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='aws_ml_exam',
            field=models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL')], default='pass', max_length=4),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='aws_practitioner_exam',
            field=models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL')], default='pass', max_length=4),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='blockchain_exam',
            field=models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL')], default='pass', max_length=4),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='date_of_enrollment',
            field=models.DateField(default='11/11/1111'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='date_of_graduation',
            field=models.DateField(default='11/11/1111'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='dissertation',
            field=models.CharField(default='pass', max_length=50),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='job_placement',
            field=models.CharField(default='R&D Lab', max_length=100),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='python_associate_exam',
            field=models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL')], default='pass', max_length=4),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='python_entry_level',
            field=models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL')], default='pass', max_length=4),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='quiz_score',
            field=models.IntegerField(default=0),
        ),
    ]
