# Generated by Django 3.1.1 on 2021-11-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0004_auto_20211129_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='aws_practitioner_exam',
        ),
    ]
